# These relationships have no dependencies. They are very similar to UDFs except that they have more control over the response.
# (UDFs are scoped to a single response that they generate a value for, while a relationship may return any response).
file: drug_relationships.py
relationships:
  - name: take_presc_meds
    # # These are the frequency distributions for each medication
    kwargs:
      name_of_rx_med1:
        response_name:  "drug1"
      name_of_rx_med2:
        response_name:  "drug2"
      name_of_rx_med3:
        response_name:  "drug3"
      name_of_rx_med4:
        response_name:  "drug4"
      name_of_rx_med5:
        response_name:  "drug5"
      name_of_rx_med6:
        response_name:  "drug6"
      name_of_rx_med7:
        response_name:  "drug7"
      name_of_rx_med8:
        response_name:  "drug8"
      name_of_rx_med9:
        response_name:  "drug9"
      name_of_rx_med10:
        response_name:  "drug10"
      name_of_rx_med11:
        response_name:  "drug11"
      name_of_rx_med12:
        response_name:  "drug12"
      name_of_rx_med13:
        response_name:  "drug13"
      name_of_rx_med14:
        response_name:  "drug14"
      name_of_rx_med15:
        response_name:  "drug15"