# Fake relationships, just something that a user can discover
file: fake_relationships.py
relationships:
  - name: insomnia_vaping
    kwargs:
      config:
        rarely: 1.1
        some_days: 1.35
        every_day: 1.75
