# These relationships are not necessarily backed by any data.
# They are just supposed to be something that a user can discover in the dataset.
file: fake_relationships.py
relationships:
  - name: insomnia_vaping
    kwargs:
      config:
        rarely: 1.1
        some_days: 1.35
        every_day: 1.75
