# These are general relationships required for response consistency across variables within the Tier2_RADxUP_relationships.
file: Tier2_RADxUP_relationships.py
# We can define as many relationships as we want in the Python file.
# But only the relationships configured under `relationships` here are going to actually be used during generation.
# We can add a "#" to the start of all the lines concerning a specific relationship to disable it.
relationships:
  - name: no_consent
  - name: race_ethn_race
  - name: race_ethn_race_islander
  - name: positive_covid
  - name: self_reported_height_coded
  - name: self_reported_weight_units
  - name: vaccine_acceptance
  - name: bio_sex_birth_2   
  - name: take_presc_meds