# These are general relationships required for response consistency across variables within the Tier2_RADxUP_relationships.
file: Tier2_RADxUP_relationships.py
# We can define as many relationships as we want in the Python file.
# But only the relationships configured under `relationships` here are going to actually be used during generation.
# We can add a "#" to the start of all the lines concerning a specific relationship to disable it.
relationships:
  - name: no_consent
  - name: race_ethn_race
  - name: race_ethn_race_islander
  - name: positive_covid
  - name: self_reported_height_coded
  - name: self_reported_weight_units
  - name: vaccine_acceptance
  - name: bio_sex_birth_2   
  - name: take_presc_meds
  - name: lifetime_use_alcohol
  - name: comp_thrombosis
  - name: lab_tests_performed
  - name: viral_positive
  - name: cardio_assessment
  - name: assessment_other
  - name: pulm_othertest
  - name: imaging_other
  - name: ct_brain
  - name: ct_chest
  - name: ct_abdomen
  - name: lung_ultrasound
  - name: vasc_ultrasound
  - name: ab_ultrasound
  - name: neonatal_ultrasound
  - name: mri_brain
  - name: mri_spine
  - name: mri_abdomen
  - name: imaging_other
  - name: medications_antibiotics
  - name: medications_diabetic
  - name: medications_other
  - name: patient_death
  - name: discharge_location
  - name: treatment_other
  - name: treatment_ongoing
  - name: breakfast_precovid
  - name: child_iep
  - name: schooling_middle
  - name: schooling_present
  - name: hi_loss_covid
  - name: hc_notrec
  - name: special_ser
  - name: use_meds
  - name: any_med_condition
  - name: more_care
  - name: any_care_condition
  - name: lim_abil
  - name: lim_abil_condition
  - name: therapy
  - name: therapy_condition
  - name: treatment
  - name: doc_question_yr
